### ISSUE TITLE
Setup to generate documentation

### ISSUE THREAD

**Issue by lorenzschmid** [tgingold-cern/cheby#14]
Hi @tgingold-cern

I was wondering about the current setup you are using to build the documentation? Looking at the `doc/Makefile`, you seem to use [Asciidoctor](https://asciidoctor.org/) (the Ruby version) as well as a script (`a2x`) from an older implementation of [AsciiDoc](https://asciidoc-py.github.io/) (the Python version). I could not reproduce that setup but managed to generate a PDF using [Asciidoctor PDF](https://docs.asciidoctor.org/pdf-converter/latest/) (based on the Ruby version). Although, the design of the PDF ended up being different (probably due to missing templates). Would you mind

- [ ] elaborating on the setup you are using at CERN (including all dependencies),
- [ ] preferably adding the setup to generate the PDF in an automated way (e.g. GitLab CI pipeline),
- [ ] update the PDF currently included in the repository and since changed (e.g. with #11 or #12)

**Comment by tgingold-cern** [comment]
I am using the tools that are available with CentOS-7 (sure, that's old).

I will agree to switch to Asciidoctor PDF.

I will regenerate the doc.

**Comment by tgingold-cern** [comment]
Also, I have installed my own version of texlive (2019) to avoid errors with a2x.

**Comment by tgingold-cern** [comment]
Looks ok to me.  Can you create a PR so that I can easily test on my setup ?
(I suppose you also have modified doc/Makefile)
